version: "3"
services:
  elasticsearch:
    image: blacktop/elasticsearch:x-pack-7.4.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elastinet
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  kibana:
    depends_on:
      - elasticsearch
    image: blacktop/kibana:x-pack-7.4.0
    environment:
      - xpack.reporting.enabled=false
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
      - elastinet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s

  filebeat:
    depends_on:
      - elasticsearch
      - kibana
    image: blacktop/filebeat:7.4.0
    links:
      - kibana
      - elasticsearch
    volumes:
      - ./pcap:/pcap
    command: -e --strict.perms=false -E setup.kibana.host=kibana:5601 -E output.elasticsearch.hosts=["elasticsearch:9200"]
    networks:
      - elastinet
    restart: on-failure

  zeek:
    depends_on:
      - filebeat
    build: ./elastic
    image: blacktop/zeek:elastic
    volumes:
      - ./pcap:/pcap
    cap_add:
      - NET_RAW
    network_mode: "host"
    command: -i af_packet::eth1 local

networks:
  elastinet:
    driver: bridge
