filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /pcap/*.log
  json.keys_under_root: true
  json.add_error_key: true
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
setup.kibana:
  host: "kibana:5601"
